postgres:
  image: postgres
  environment:
    POSTGRES_DB: wongames
    POSTGRES_USER: wongames
    POSTGRES_PASSWORD: wongames
  volumes:
    - ./data:/var/lib/postgresql/data
  ports:
    - '5432:5432' 